//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hrm_v4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIALES
    {
        public int ID_HIST { get; set; }
        public int ID_EMPLEADO { get; set; }
        public int ID_USUARIO { get; set; }
        public string ACCION { get; set; }
        public string JUSTIFICACION { get; set; }
    
        public virtual EMPLEADOS EMPLEADOS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
