//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hrm_v4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUESTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PUESTOS()
        {
            this.EMPLEADOS = new HashSet<EMPLEADOS>();
        }
    
        public int PTS_ID { get; set; }
        public string ID_PUESTO { get; set; }
        public string NOMBRE { get; set; }
        public int DEPARTAMENTO { get; set; }
        public string NIVEL_ACADEMICO { get; set; }
        public string EXP_MIN { get; set; }
        public string EXP_DESEADA { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual DEPARTAMENTOS DEPARTAMENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADOS> EMPLEADOS { get; set; }
    }
}
